export const defaultSite = {
  name: "Ekika Cultural Experience",
  shortName: "Ekika",
  email: "hello@ekikaexperience.ug",
  phoneDisplay: "+256 700 000 000",
  phoneHref: "tel:+256700000000",
  whatsappUrl: "https://wa.me/256700000000",
  address: ["Kabale-Lake Bunyonyi Road", "Kigezi Highlands, South Western Uganda", "P.O. Box 42, Kabale"],
  locationLabel: "Kabale District, Kigezi Region, Uganda",
};

export const defaultExperiences = [
  {
    id: "food-cooking",
    title: "Cultural Food Tasting & Cooking Lessons",
    description: "Master the art of preparing traditional millet bread (Oburo) and enjoy the rich, earthy flavors of our highland soil.",
    priceCents: 4500,
    duration: "3 Hours",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDs1DwY3lmZUoGlvfZoINxau6S8Hz3Jj4HzIKgdzDst0dK9yx6I3KYH4Sc6hc0TPTdshhegVCwf2rQoxzWSSj3YjHuhnEXn4LP_vLwV3Q9w5mxyOkU-6l3qvbxDGUjnihHA3X52eD_meCbolk9HjaYb6AynB3_GnGJ0qGjJoQpDCrUf8uDNzuP5MD7wwoy_qjyBu2tMysDL0kcWULW1AvuduuLGKS9YY1jIZBDmMW_VWxmOjtx3ldzzC3SeDgFOLrzrRqbL7j7QVA0",
    tag: "Most Popular",
    included: ["Traditional lunch included", "Local host guide", "Recipe notes"],
  },
  {
    id: "storytelling",
    title: "Story Telling Sessions",
    description: "Gather around the evening embers as elders recount legends of the ancestors and the spirits of the mountains.",
    priceCents: 2500,
    duration: "2 Hours",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA7966SouRc5zHc0oFnseCvOV7vUuvMV7AE3cDz6qmC0AzSDlh1dBIl7i0znUREFlVRqMCj3JLtkLDCWqGjOmUB2KxtEjTPQQcIxQxRAIEqjHx5AEHqPgvPtmBPgS33HQ0Dm_wPvGkqjRcBt_NlxhUNi5KjY-nU9Du3sEfXpawiYH5uvFFToHbKMqaN_efTrcyzWR5v2lQNnKcjVoqmtbGHKDmXSmBXx4DB_heV8dVnLpErzsFp3PNE04YUcLfDPdlTX02tY410dVQ",
    tag: "Evening",
    included: ["Elder-led session", "Tea by the hearth", "Cultural Q&A"],
  },
  {
    id: "traditional-games",
    title: "Traditional Games",
    description: "Test your agility and strength with authentic Kiga sports, from wrestling to traditional target throwing.",
    priceCents: 2000,
    duration: "2 Hours",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAQQOa1V3l9rh9DrmmIH-g20B5CFV_Git0PETHxXW-fhnwRHdVmmJ2TArZFaZ7YOGy28335aiQxay2CnWeaVnbyX4zoGW2DJjH12ydp_lc9kAwWpwgqasnhZKfJHO3OT4YF_-HDDIxAtBuFZCaPaAga8yWHn4VeoVO40o8TkSQHuYkLDLLIiwCer6xwDBOzq98eZurNV5HUE7GI9s-HDQTR9PQI-uFtrk9AHsguHbjg6egw8uteO3MOFbKIr2N6JsZE_BpZt76_mSY",
    tag: "Active",
    included: ["Group activities", "Guide supervision", "Family friendly"],
  },
  {
    id: "attire",
    title: "Ekika Dressing & Attire",
    description: "Learn the symbolism behind our traditional skins and beads. Includes a portrait session in full attire.",
    priceCents: 3500,
    duration: "2 Hours",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAzag7Vw_-fg_tK1fZBJ9eqTQr60G0a8LaHgsfm8kLZDplro_-sYStc5T6Y8tQmVq4bed1CL44nkYIn3uJdoe9ahV0p3rs0WJHTKso49-6cYCLuD2h7D8h6qDJWsqIzNTCZ1Yuqc5wql_C4ikAKjOvsSCqVbOhcnOdk068K2vTctcJURUTlHSVD3PWCoCKuB2Q_unpv7QPgzewqjjGVKIrCXGvpdEPkKYLraNPM9HQrhpP1bgN8BFtMmSQ4KiWsomTKMlNFDm9F08",
    tag: "Portrait",
    included: ["Attire guidance", "Portrait session", "Symbolism talk"],
  },
  {
    id: "full-day",
    title: "Full Cultural Day Package",
    description: "The definitive Kigezi journey. Includes all activities plus a traditional banquet and highland trekking.",
    priceCents: 12000,
    duration: "8 Hours",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCUF5Q0elMs1ZTJ_ulIBlxqFQbruH-KrYah0t-NagmCbAKI3N-YwphzPXuoqk9f90lafZpEGhv0rzw6u8ZWS13EV1IihaKToXHxsvdk3LBsQpD09L0syToSfhChPjkBE2K017w8LT70bi9JpAV24K3ixguF0wZTFnEduYtyKw7Ma6OijuRIA2Un-TUEwi2h2787Q-DNlT2nVSENhIlg-my0eoSjl_vdcgzgLTdnm2q2oD6wxepoESsiuq7D2Z4s6q0IPkdqrTqmmIY",
    tag: "Best Value",
    included: ["Traditional lunch included", "Professional photography", "Highland trekking"],
  },
];
